CREATE DATABASE DO_AN_CUOI_KI
USE DO_AN_CUOI_KI
--DROP DATABASE DO_AN_CUOI_KI

CREATE TABLE INFORMATION
(
	MSSV NVARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH VARCHAR(50) NOT NULL,
)
ALTER TABLE INFORMATION ADD
	CONSTRAINT PK_MSSV_INFORMATION PRIMARY KEY(MSSV)

CREATE TABLE IMAGE
(
	MSSV NVARCHAR(10) NOT NULL,
	LINK_IMAGE VARCHAR(50) NOT NULL
)
ALTER TABLE IMAGE ADD
	CONSTRAINT PK_MSSV_IMAGE PRIMARY KEY(MSSV),
	CONSTRAINT FK_MSSV_IMAGE FOREIGN KEY(MSSV) REFERENCES INFORMATION (MSSV)

CREATE TABLE QRCODE
(
	MSSV NVARCHAR(10) NOT NULL,
	LINK_QR VARCHAR(50) NOT NULL
)
ALTER TABLE QRCODE ADD
	CONSTRAINT PK_MSSV_QRCODE PRIMARY KEY(MSSV),
	CONSTRAINT FK_MSSV_QRCODE FOREIGN KEY(MSSV) REFERENCES INFORMATION (MSSV)

SET DATEFORMAT dmy